version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    env_file: ./.env
    environment:
      MONGODB_URI: ${MONGODB_URI}
      TEST_MONGODB_URI: ${TEST_MONGODB_URI}
      PORT: ${PORT}
