GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json


{   
        "title": "Test",
        "author": "Steve Daniels",
        "url": "www.bla-bla4654",
        "likes": 3
        
        
}

###
DELETE http://localhost:3003/api/blogs/647f2e5f9a4dd19b170c446e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QyIiwiaWQiOiI2NDdmMmI2YmViMzhhMWIxZjEyZmU1MjAiLCJpYXQiOjE2ODYwNTU4MDQsImV4cCI6MTY4NjA1OTQwNH0.0g0kaFeeqMN7iIGfkPXtlwfjCym0pTpxXGl4WzQeJqg

