GET http://localhost:3003/api/users/

###
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "Test2",
    "name": "Roman",
    "password":"dNX3sTE3" 
     
}

###

DELETE http://localhost:3003/api/users/647f2b2d395081035bf93684