GET http://localhost:3003/api/users/

###
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "Roman",
    "name": "Roman",
    "password":"dNX3sTE3" 
     
}

###

DELETE http://localhost:3003/api/users/64808a6568b40fa30b1e7116